export const types = {
  LEFT_TOP: "LEFT_TOP",
  LEFT_DOWN: "LEFT_DOWN",
  RIGHT_TOP: "RIGHT_TOP",
  RIGHT_DOWN: "RIGHT_DOWN",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
};
